REPLACE INTO xcart_languages VALUES ('en','module_name_Abandoned_Cart_Reminder','Abandoned Cart Reminder','Modules');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_abandoned_cart_notification_with_coupon_subj','Special offer for your visit at {{company}}','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_abandoned_cart_notification_without_coupon_subj','Humble follow-up email about your last visit at {{company}}','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_cart_has_items','Your shopping cart currently contains the following items','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_hello','Hello {{name}}!','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_notification_message','You recently visited our site {{company_name}} ({{company_site}}), and we noticed that you still have a few items in your shopping cart. We would like to offer you a special discount towards your next purchase! Simply enter the coupon code <strong>{{coupon}}</strong> at checkout and you will {{coupon_bonus}} on your current pending order. The coupon code expires on {{expiration_time}}.\n\nIf you have any questions or require special assistance, please contact us by replying to this email. We would be happy to help you.','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_notification_message_discount','save <strong>{{coupon_value}}</strong>','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_notification_message_freeship','get <strong>free shipping</strong>','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_notification_without_coupon_message','You recently visited our site {{company_name}} ({{company_site}}),  and we noticed that you added some items to your shopping cart, but did not fully complete your order. We just wanted to make sure you did not encounter any problems with checkout on our site. If there is anything we can do to assist you with your online order, please do not hesitate to contact us by replying to this email.','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_visit_us','You can go to your shopping cart directly by clicking the special link below: {{return_link}}','E-Mail');
REPLACE INTO xcart_languages VALUES ('en','eml_abcr_visit_us_html','You can go to your shopping cart directly by clicking <a href="{{return_link}}">the special link</a>.','E-Mail');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_abandoned_carts', 'Abandoned Carts', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_are_you_sure_to_delete_abandoned_cart', 'Are you sure to delete this abandoned cart?', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_are_you_sure_to_delete_abandoned_carts', 'Are you sure to delete selected abandoned carts?', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_are_you_sure_to_send_notifications_to_carts', 'Are you sure to notify abandoned carts?', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_attach_coupon', 'Attach coupon', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_coupon_parameters', 'Coupon parameters', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_create_order', 'Create order', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_expiration_date', 'Expiration date', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_filter_by_date', 'Filter by date', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_found_abandoned_carts', 'Found abandoned carts', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_go_to_abandoned_carts', 'Go to abandoned carts list', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_is_notified', 'Is notified?', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_last', 'last', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_month_total', 'Month total', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_no_abandoned_carts_found', 'No abandoned carts were found', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_no_abandoned_carts_selected', 'No abandoned carts are selected', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_order_statistic', 'Cart recovery statistic', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_search_by_date', 'Search by date', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_search_by_email_or_login', 'Search by email or customer login', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_search_for_abandoned_carts', 'Search for abandoned carts', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_send_notification', 'Send notification', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_send_notification_to_cart', 'Send notification to this cart owner', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_send_notifications_to_carts', 'Send notifications to selected cart owners', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_time', 'time', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_times', 'times', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_total_revenue_recovered', 'Total revenue recovered', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_coupon_parameters_incorrect', 'Coupon parameters are incorrect', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_no_abandoned_carts_selected', 'No abandoned carts are selected', 'Label');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_notification_to_customer_was_not_sent','Notification to {{customer}} customer has not been sent because all the products in the abandoned cart are not available for sale or out of stock.','Text');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_notifications_to_customers_were_not_sent','Notifications to {{customers}} customers have not been sent because all the products in the abandoned carts are not available for sale or out of stock.','Text');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_notification_was_sent','Notification to {{customer}} was properly sent','Text');
REPLACE INTO xcart_languages VALUES ('en', 'msg_abcr_adm_notifications_were_sent','Notifications to {{customers}} were properly sent','Text');

REPLACE INTO xcart_languages VALUES ('en', 'lbl_abcr_not_owned_product', 'Product from another provider', 'Label');

